#! /bin/sh

module load dev/java/6-sun

java -Xmx2g -jar /opt/muTect-1.1.4/muTect-1.1.4.jar \
--analysis_type MuTect \
--reference_sequence/hg19.fa \
--dbsnp dbsnp137/ucsc_dbsnp/dbsnp137.vcf \
--input_file:normal bam_output/DNA_N.sorted.MarkDup.realn.fixed.bam \
--input_file:tumor bam_output/DNA_T.sorted.MarkDup.realn.fixed.bam \
--out somaticMutatoin/TvsN.call_stats.txt \
--coverage_file somaticMutatoin/TvsN.coverage.wig.txt \
--vcf somaticMutatoin/TvsN.vcf

module unload dev/java/6-sun
